[WIP]オリジナルのsignTypedDataでpermitが成功しない
noplan-inc/cloud-cryptographic-wallet pull request #2
Opened 2023-12-03 07:32 UTC by mo29cg

2023-12-06 05:05 UTC, serinuntius approved these changes

2023-12-06 05:05 UTC, serinuntius commented on test/e2e/ethers6/ethers-signTypedData.spec.ts
> +  const provider = new ethers.JsonRpcProvider(process.env.MUMBAI_RPC);
[ask] これ今更かもしれないけど、Hardhatでやってないのって意味あるんだっけ？

昔、テストネットでも行けるか検証して欲しいって言ったけど、常にテストネットである必要はないので、.envでRPC渡してローカルとCIで決めれるようにする？

2023-12-06 05:05 UTC, serinuntius commented on test/e2e/ethers6/ethers-signTypedData.spec.ts
> +    "0xd7602dd73fd247bd177117131583b4c0ba8ebaab32a0883ed7b1cf67b8826e76";
[must] テストネットとはいえ、privateKeyをpublicなrepoに置きたくないです。

- 別の鍵に変えたいです
- 環境変数に変えたいです
- hardhat前提なら都度createWalletして、ガス補填するとかでも良い

2023-12-06 05:05 UTC, serinuntius commented on test/e2e/ethers6/ethers-signTypedData.spec.ts
> +
[must]

追加でコントラクトのnonceが上がってるかチェックして欲しいです!

2023-12-06 05:06 UTC, serinuntius requested changes
間違えた request changes

2023-12-06 05:11 UTC, serinuntius commented on packages/ethers-adapter/package.json
> +  "version": "0.1.0",
[imo]
あ、ここのバージョン下げるのは危険な気がする。

https://www.npmjs.com/package/@cloud-cryptographic-wallet2/ethers-adapter

って思ったけど、今 リリースされてるのは `0.1.0` なのか。 次リリースするなら `0.2.0` 説か。

`0.2.0` で書いて、リリースも `0.2.0` で行きましょうか？

2023-12-11 03:46 UTC, mo29cg commented on test/e2e/ethers6/ethers-signTypedData.spec.ts
> +    "0xd7602dd73fd247bd177117131583b4c0ba8ebaab32a0883ed7b1cf67b8826e76";
そうします！

2023-12-16 05:01 UTC, mo29cg commented on packages/ethers-adapter/package.json
> +  "version": "0.1.0",
これ多分、npmに上げるときに0.1.0にして、その差分をgithubに上げるの忘れてました
今回のは0.2.0にします！

2023-12-18 01:52 UTC, serinuntius approved these changes

2023-12-18 06:20 UTC, merged